redirects:  
  kit-accessibilite: gerer-son-produit/les-standards/accessibilite-and-inclusion/kit-accessibilite/README.md
  check-accessibilite: travailler-chez-beta.gouv.fr/se-former/se-former-en-ligne/formation-a-laccessibilite/10-choses-faciles-a-verifier-pour-un-site-plus-accessible.md
  welcome: travailler-chez-beta.gouv.fr/to-do-darrivee/README.md
  welcome-dev: /travailler-chez-beta.gouv.fr/les-differents-metiers/developpeur.se/kit-de-demarrage.md
  standards: gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-fais-des-choix-technologique/standards-de-qualite-beta.gouv.fr.md
  rgpd: gerer-son-produit/les-standards/protection-des-donnees-personnelles/README.md
  formation: travailler-chez-beta.gouv.fr/se-former/README.md
  dashlord: les-outils-de-la-communaute/dashlord/README.md
  dsfr: gerer-son-produit/les-standards/design/dsfr/README.md
